/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ReviewInput = IDL.Record({
  'shopId' : IDL.Nat,
  'comment' : IDL.Text,
  'stars' : IDL.Nat,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'shopId' : IDL.Nat,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'comment' : IDL.Text,
  'stars' : IDL.Nat,
});
export const ShopCategory = IDL.Variant({
  'JuiceShop' : IDL.Null,
  'SnackShop' : IDL.Null,
  'StreetFood' : IDL.Null,
  'Cafe' : IDL.Null,
  'Bakery' : IDL.Null,
  'Other' : IDL.Text,
  'Restaurant' : IDL.Null,
});
export const Shop = IDL.Record({
  'id' : IDL.Nat,
  'latitude' : IDL.Float64,
  'photoKeys' : IDL.Vec(IDL.Text),
  'ownerId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'openingTime' : IDL.Text,
  'offers' : IDL.Vec(IDL.Text),
  'isOpen' : IDL.Bool,
  'longitude' : IDL.Float64,
  'address' : IDL.Text,
  'category' : ShopCategory,
  'closingTime' : IDL.Text,
  'rating' : IDL.Float64,
  'phone' : IDL.Text,
  'reviewCount' : IDL.Nat,
  'instagramId' : IDL.Opt(IDL.Text),
});
export const ShopInput = IDL.Record({
  'latitude' : IDL.Float64,
  'photoKeys' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'openingTime' : IDL.Text,
  'offers' : IDL.Vec(IDL.Text),
  'longitude' : IDL.Float64,
  'address' : IDL.Text,
  'category' : ShopCategory,
  'closingTime' : IDL.Text,
  'phone' : IDL.Text,
  'instagramId' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addReview' : IDL.Func([ReviewInput], [Review], []),
  'extendShopHours' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllShops' : IDL.Func([], [IDL.Vec(Shop)], ['query']),
  'getFavorites' : IDL.Func([], [IDL.Vec(Shop)], ['query']),
  'getOwnerShop' : IDL.Func([], [IDL.Opt(Shop)], ['query']),
  'getReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getShopById' : IDL.Func([IDL.Nat], [IDL.Opt(Shop)], ['query']),
  'getShopsByCategory' : IDL.Func([ShopCategory], [IDL.Vec(Shop)], ['query']),
  'initSeed' : IDL.Func([], [], []),
  'registerShop' : IDL.Func([ShopInput], [Shop], []),
  'searchShops' : IDL.Func([IDL.Text], [IDL.Vec(Shop)], ['query']),
  'toggleFavorite' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'updateShopHours' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateShopStatus' : IDL.Func([IDL.Bool], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ReviewInput = IDL.Record({
    'shopId' : IDL.Nat,
    'comment' : IDL.Text,
    'stars' : IDL.Nat,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'shopId' : IDL.Nat,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'comment' : IDL.Text,
    'stars' : IDL.Nat,
  });
  const ShopCategory = IDL.Variant({
    'JuiceShop' : IDL.Null,
    'SnackShop' : IDL.Null,
    'StreetFood' : IDL.Null,
    'Cafe' : IDL.Null,
    'Bakery' : IDL.Null,
    'Other' : IDL.Text,
    'Restaurant' : IDL.Null,
  });
  const Shop = IDL.Record({
    'id' : IDL.Nat,
    'latitude' : IDL.Float64,
    'photoKeys' : IDL.Vec(IDL.Text),
    'ownerId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'openingTime' : IDL.Text,
    'offers' : IDL.Vec(IDL.Text),
    'isOpen' : IDL.Bool,
    'longitude' : IDL.Float64,
    'address' : IDL.Text,
    'category' : ShopCategory,
    'closingTime' : IDL.Text,
    'rating' : IDL.Float64,
    'phone' : IDL.Text,
    'reviewCount' : IDL.Nat,
    'instagramId' : IDL.Opt(IDL.Text),
  });
  const ShopInput = IDL.Record({
    'latitude' : IDL.Float64,
    'photoKeys' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'openingTime' : IDL.Text,
    'offers' : IDL.Vec(IDL.Text),
    'longitude' : IDL.Float64,
    'address' : IDL.Text,
    'category' : ShopCategory,
    'closingTime' : IDL.Text,
    'phone' : IDL.Text,
    'instagramId' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addReview' : IDL.Func([ReviewInput], [Review], []),
    'extendShopHours' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllShops' : IDL.Func([], [IDL.Vec(Shop)], ['query']),
    'getFavorites' : IDL.Func([], [IDL.Vec(Shop)], ['query']),
    'getOwnerShop' : IDL.Func([], [IDL.Opt(Shop)], ['query']),
    'getReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getShopById' : IDL.Func([IDL.Nat], [IDL.Opt(Shop)], ['query']),
    'getShopsByCategory' : IDL.Func([ShopCategory], [IDL.Vec(Shop)], ['query']),
    'initSeed' : IDL.Func([], [], []),
    'registerShop' : IDL.Func([ShopInput], [Shop], []),
    'searchShops' : IDL.Func([IDL.Text], [IDL.Vec(Shop)], ['query']),
    'toggleFavorite' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'updateShopHours' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateShopStatus' : IDL.Func([IDL.Bool], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };