/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Review {
  'id' : bigint,
  'shopId' : bigint,
  'userId' : Principal,
  'createdAt' : bigint,
  'comment' : string,
  'stars' : bigint,
}
export interface ReviewInput {
  'shopId' : bigint,
  'comment' : string,
  'stars' : bigint,
}
export interface Shop {
  'id' : bigint,
  'latitude' : number,
  'photoKeys' : Array<string>,
  'ownerId' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'openingTime' : string,
  'offers' : Array<string>,
  'isOpen' : boolean,
  'longitude' : number,
  'address' : string,
  'category' : ShopCategory,
  'closingTime' : string,
  'rating' : number,
  'phone' : string,
  'reviewCount' : bigint,
  'instagramId' : [] | [string],
}
export type ShopCategory = { 'JuiceShop' : null } |
  { 'SnackShop' : null } |
  { 'StreetFood' : null } |
  { 'Cafe' : null } |
  { 'Bakery' : null } |
  { 'Other' : string } |
  { 'Restaurant' : null };
export interface ShopInput {
  'latitude' : number,
  'photoKeys' : Array<string>,
  'name' : string,
  'openingTime' : string,
  'offers' : Array<string>,
  'longitude' : number,
  'address' : string,
  'category' : ShopCategory,
  'closingTime' : string,
  'phone' : string,
  'instagramId' : [] | [string],
}
export interface _SERVICE {
  'addReview' : ActorMethod<[ReviewInput], Review>,
  'extendShopHours' : ActorMethod<[string], boolean>,
  'getAllShops' : ActorMethod<[], Array<Shop>>,
  'getFavorites' : ActorMethod<[], Array<Shop>>,
  'getOwnerShop' : ActorMethod<[], [] | [Shop]>,
  'getReviews' : ActorMethod<[bigint], Array<Review>>,
  'getShopById' : ActorMethod<[bigint], [] | [Shop]>,
  'getShopsByCategory' : ActorMethod<[ShopCategory], Array<Shop>>,
  'initSeed' : ActorMethod<[], undefined>,
  'registerShop' : ActorMethod<[ShopInput], Shop>,
  'searchShops' : ActorMethod<[string], Array<Shop>>,
  'toggleFavorite' : ActorMethod<[bigint], boolean>,
  'updateShopHours' : ActorMethod<[string, string], boolean>,
  'updateShopStatus' : ActorMethod<[boolean], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];