/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type ShopCategory = {
    __kind__: "JuiceShop";
    JuiceShop: null;
} | {
    __kind__: "SnackShop";
    SnackShop: null;
} | {
    __kind__: "StreetFood";
    StreetFood: null;
} | {
    __kind__: "Cafe";
    Cafe: null;
} | {
    __kind__: "Bakery";
    Bakery: null;
} | {
    __kind__: "Other";
    Other: string;
} | {
    __kind__: "Restaurant";
    Restaurant: null;
};
export interface Shop {
    id: bigint;
    latitude: number;
    photoKeys: Array<string>;
    ownerId: Principal;
    name: string;
    createdAt: bigint;
    openingTime: string;
    offers: Array<string>;
    isOpen: boolean;
    longitude: number;
    address: string;
    category: ShopCategory;
    closingTime: string;
    rating: number;
    phone: string;
    reviewCount: bigint;
    instagramId?: string;
}
export interface ShopInput {
    latitude: number;
    photoKeys: Array<string>;
    name: string;
    openingTime: string;
    offers: Array<string>;
    longitude: number;
    address: string;
    category: ShopCategory;
    closingTime: string;
    phone: string;
    instagramId?: string;
}
export interface ReviewInput {
    shopId: bigint;
    comment: string;
    stars: bigint;
}
export interface Review {
    id: bigint;
    shopId: bigint;
    userId: Principal;
    createdAt: bigint;
    comment: string;
    stars: bigint;
}
export interface backendInterface {
    addReview(input: ReviewInput): Promise<Review>;
    extendShopHours(newClosingTime: string): Promise<boolean>;
    getAllShops(): Promise<Array<Shop>>;
    getFavorites(): Promise<Array<Shop>>;
    getOwnerShop(): Promise<Shop | null>;
    getReviews(shopId: bigint): Promise<Array<Review>>;
    getShopById(id: bigint): Promise<Shop | null>;
    getShopsByCategory(category: ShopCategory): Promise<Array<Shop>>;
    initSeed(): Promise<void>;
    registerShop(input: ShopInput): Promise<Shop>;
    searchShops(searchTerm: string): Promise<Array<Shop>>;
    toggleFavorite(shopId: bigint): Promise<boolean>;
    updateShopHours(openingTime: string, closingTime: string): Promise<boolean>;
    updateShopStatus(isOpen: boolean): Promise<boolean>;
}
import type { Shop as _Shop, ShopCategory as _ShopCategory, ShopInput as _ShopInput } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addReview(arg0: ReviewInput): Promise<Review> {
        if (this.processError) {
            try {
                const result = await this.actor.addReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReview(arg0);
            return result;
        }
    }
    async extendShopHours(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.extendShopHours(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.extendShopHours(arg0);
            return result;
        }
    }
    async getAllShops(): Promise<Array<Shop>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllShops();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllShops();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFavorites(): Promise<Array<Shop>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFavorites();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFavorites();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnerShop(): Promise<Shop | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnerShop();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnerShop();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReviews(arg0: bigint): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviews(arg0);
            return result;
        }
    }
    async getShopById(arg0: bigint): Promise<Shop | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getShopById(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShopById(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShopsByCategory(arg0: ShopCategory): Promise<Array<Shop>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShopsByCategory(to_candid_ShopCategory_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShopsByCategory(to_candid_ShopCategory_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async initSeed(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initSeed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initSeed();
            return result;
        }
    }
    async registerShop(arg0: ShopInput): Promise<Shop> {
        if (this.processError) {
            try {
                const result = await this.actor.registerShop(to_candid_ShopInput_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Shop_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerShop(to_candid_ShopInput_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Shop_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchShops(arg0: string): Promise<Array<Shop>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchShops(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchShops(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleFavorite(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleFavorite(arg0);
            return result;
        }
    }
    async updateShopHours(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShopHours(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShopHours(arg0, arg1);
            return result;
        }
    }
    async updateShopStatus(arg0: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShopStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShopStatus(arg0);
            return result;
        }
    }
}
function from_candid_ShopCategory_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShopCategory): ShopCategory {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Shop_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Shop): Shop {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Shop]): Shop | null {
    return value.length === 0 ? null : from_candid_Shop_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    latitude: number;
    photoKeys: Array<string>;
    ownerId: Principal;
    name: string;
    createdAt: bigint;
    openingTime: string;
    offers: Array<string>;
    isOpen: boolean;
    longitude: number;
    address: string;
    category: _ShopCategory;
    closingTime: string;
    rating: number;
    phone: string;
    reviewCount: bigint;
    instagramId: [] | [string];
}): {
    id: bigint;
    latitude: number;
    photoKeys: Array<string>;
    ownerId: Principal;
    name: string;
    createdAt: bigint;
    openingTime: string;
    offers: Array<string>;
    isOpen: boolean;
    longitude: number;
    address: string;
    category: ShopCategory;
    closingTime: string;
    rating: number;
    phone: string;
    reviewCount: bigint;
    instagramId?: string;
} {
    return {
        id: value.id,
        latitude: value.latitude,
        photoKeys: value.photoKeys,
        ownerId: value.ownerId,
        name: value.name,
        createdAt: value.createdAt,
        openingTime: value.openingTime,
        offers: value.offers,
        isOpen: value.isOpen,
        longitude: value.longitude,
        address: value.address,
        category: from_candid_ShopCategory_n4(_uploadFile, _downloadFile, value.category),
        closingTime: value.closingTime,
        rating: value.rating,
        phone: value.phone,
        reviewCount: value.reviewCount,
        instagramId: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.instagramId))
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    JuiceShop: null;
} | {
    SnackShop: null;
} | {
    StreetFood: null;
} | {
    Cafe: null;
} | {
    Bakery: null;
} | {
    Other: string;
} | {
    Restaurant: null;
}): {
    __kind__: "JuiceShop";
    JuiceShop: null;
} | {
    __kind__: "SnackShop";
    SnackShop: null;
} | {
    __kind__: "StreetFood";
    StreetFood: null;
} | {
    __kind__: "Cafe";
    Cafe: null;
} | {
    __kind__: "Bakery";
    Bakery: null;
} | {
    __kind__: "Other";
    Other: string;
} | {
    __kind__: "Restaurant";
    Restaurant: null;
} {
    return "JuiceShop" in value ? {
        __kind__: "JuiceShop",
        JuiceShop: value.JuiceShop
    } : "SnackShop" in value ? {
        __kind__: "SnackShop",
        SnackShop: value.SnackShop
    } : "StreetFood" in value ? {
        __kind__: "StreetFood",
        StreetFood: value.StreetFood
    } : "Cafe" in value ? {
        __kind__: "Cafe",
        Cafe: value.Cafe
    } : "Bakery" in value ? {
        __kind__: "Bakery",
        Bakery: value.Bakery
    } : "Other" in value ? {
        __kind__: "Other",
        Other: value.Other
    } : "Restaurant" in value ? {
        __kind__: "Restaurant",
        Restaurant: value.Restaurant
    } : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Shop>): Array<Shop> {
    return value.map((x)=>from_candid_Shop_n2(_uploadFile, _downloadFile, x));
}
function to_candid_ShopCategory_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShopCategory): _ShopCategory {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_ShopInput_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShopInput): _ShopInput {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latitude: number;
    photoKeys: Array<string>;
    name: string;
    openingTime: string;
    offers: Array<string>;
    longitude: number;
    address: string;
    category: ShopCategory;
    closingTime: string;
    phone: string;
    instagramId?: string;
}): {
    latitude: number;
    photoKeys: Array<string>;
    name: string;
    openingTime: string;
    offers: Array<string>;
    longitude: number;
    address: string;
    category: _ShopCategory;
    closingTime: string;
    phone: string;
    instagramId: [] | [string];
} {
    return {
        latitude: value.latitude,
        photoKeys: value.photoKeys,
        name: value.name,
        openingTime: value.openingTime,
        offers: value.offers,
        longitude: value.longitude,
        address: value.address,
        category: to_candid_ShopCategory_n8(_uploadFile, _downloadFile, value.category),
        closingTime: value.closingTime,
        phone: value.phone,
        instagramId: value.instagramId ? candid_some(value.instagramId) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "JuiceShop";
    JuiceShop: null;
} | {
    __kind__: "SnackShop";
    SnackShop: null;
} | {
    __kind__: "StreetFood";
    StreetFood: null;
} | {
    __kind__: "Cafe";
    Cafe: null;
} | {
    __kind__: "Bakery";
    Bakery: null;
} | {
    __kind__: "Other";
    Other: string;
} | {
    __kind__: "Restaurant";
    Restaurant: null;
}): {
    JuiceShop: null;
} | {
    SnackShop: null;
} | {
    StreetFood: null;
} | {
    Cafe: null;
} | {
    Bakery: null;
} | {
    Other: string;
} | {
    Restaurant: null;
} {
    return value.__kind__ === "JuiceShop" ? {
        JuiceShop: value.JuiceShop
    } : value.__kind__ === "SnackShop" ? {
        SnackShop: value.SnackShop
    } : value.__kind__ === "StreetFood" ? {
        StreetFood: value.StreetFood
    } : value.__kind__ === "Cafe" ? {
        Cafe: value.Cafe
    } : value.__kind__ === "Bakery" ? {
        Bakery: value.Bakery
    } : value.__kind__ === "Other" ? {
        Other: value.Other
    } : value.__kind__ === "Restaurant" ? {
        Restaurant: value.Restaurant
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
